<?php

$paisesArr = array(
  0 => array(
    'id' => 0,
    'nombre' => 'España',
    "continente" => "Europa",
    'precio' => '$45010',
    'descripcion' => 'VISITANDO: España MADRID, SANTIAGO DE COMPOSTELA -RINLO - CABO VIDIO - LA MANJOYA - COVADONGA - CUEVAS DEL SOPLAO - SANTANDER - BILBAO - SAN SEBASTIAN.',
    'descripcion_details' => array("ESPANIA Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/1.png',
    'destacado' => false,
  ),
  1 => array(
    'id' => 1,
    'nombre' => 'Francia',
    "continente" => "Europa",
    'precio' => '$45020',
    'descripcion' => 'VISITANDO: Francia MADRID, SANTIAGO DE COMPOSTELA -RINLO - CABO VIDIO - LA MANJOYA - COVADONGA - CUEVAS DEL SOPLAO - SANTANDER - BILBAO - SAN SEBASTIAN.',
    'descripcion_details' => array("ESPANIA Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/1.png',
    'destacado' => true,
  ),
  2 => array(
    'id' => 2,
    'nombre' => 'Italia',
    "continente" => "Europa",
    'precio' => '$43000',
    'descripcion' => 'VISITANDO: Italia MADRID, SANTIAGO DE COMPOSTELA -RINLO - CABO VIDIO - LA MANJOYA - COVADONGA - CUEVAS DEL SOPLAO - SANTANDER - BILBAO - SAN SEBASTIAN.',
    'descripcion_details' => array("ESPANIA Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/1.png',
    'destacado' => false,
  ),
  3 => array(
    'id' => 3,
    'nombre' => 'Alemania',
    "continente" => "Europa",
    'precio' => '$44000',
    'descripcion' => 'VISITANDO: Alemania, SANTIAGO DE COMPOSTELA -RINLO - CABO VIDIO - LA MANJOYA - COVADONGA - CUEVAS DEL SOPLAO - SANTANDER - BILBAO - SAN SEBASTIAN.',
    'descripcion_details' => array("ESPANIA Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/1.png',
    'destacado' => true,
  ),
  4 => array(
    'id' => 4,
    'nombre' => 'Estados Unidos',
    "continente" => "America del Norte",
    'precio' => '$20000',
    'descripcion' => 'Estados Unidos Visitando: Bsssoston / Quebec / Montreal / Ottawa / Toronto / Niagara Falls - Incluye: boleto por American Airlines. Desayunos Americanos. ALIMENTACIÓN: Desayuno diario incluidos. Opcional: asistencia CORIS con seguro de cancelación USD 36 por persona.',
    'descripcion_details' => array("Estados Unidos Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/2.png',
    'destacado' => false,
  ),
  5 => array(
    'id' => 5,
    'nombre' => 'Canada',
    "continente" => "America del Norte",
    'precio' => '$20000',
    'descripcion' => 'Canada Visitando: Bsssoston / Quebec / Montreal / Ottawa / Toronto / Niagara Falls - Incluye: boleto por American Airlines. Desayunos Americanos. ALIMENTACIÓN: Desayuno diario incluidos. Opcional: asistencia CORIS con seguro de cancelación USD 36 por persona.',
    'descripcion_details' => array("Estados Unidos Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/2.png',
    'destacado' => true,
  ),
  6 => array(
    'id' => 6,
    'nombre' => 'Mexico',
    "continente" => "America del Norte",
    'precio' => '$20000',
    'descripcion' => 'Mexico Visitando: Bsssoston / Quebec / Montreal / Ottawa / Toronto / Niagara Falls - Incluye: boleto por American Airlines. Desayunos Americanos. ALIMENTACIÓN: Desayuno diario incluidos. Opcional: asistencia CORIS con seguro de cancelación USD 36 por persona.',
    'descripcion_details' => array("Estados Unidos Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/2.png',
    'destacado' => false,
  ),
  7 => array(
    'id' => 7,
    'nombre' => 'Brasil',
    "continente" => "America del Sur",
    'precio' => '$60030',
    'descripcion' => 'INCLUYE: Brasil GUÍA: Operado con guía en español e inglés. Pasaje (Latam Airlines).   ALOJAMIENTO: 3 noches de alojamiento en Lima. 1 noche de alojamiento en Paracas. 2 noches de alojamiento en Cusco. 1 noche de alojamiento en Aguas Calientes. ALIMENTACIÓN: Desayuno diario incluidos. Opcional: asistencia CORIS con seguro de cancelación USD 36 por persona.',
    'descripcion_details' => array("Argentina Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/3.png',
    'destacado' => true,
  ),
  8 => array(
    'id' => 8,
    'nombre' => 'Argentina',
    "continente" => "America del Sur",
    'precio' => '$60030',
    'descripcion' => 'INCLUYE: Argentina GUÍA: Operado con guía en español e inglés. Pasaje (Latam Airlines).   ALOJAMIENTO: 3 noches de alojamiento en Lima. 1 noche de alojamiento en Paracas. 2 noches de alojamiento en Cusco. 1 noche de alojamiento en Aguas Calientes. ALIMENTACIÓN: Desayuno diario incluidos. Opcional: asistencia CORIS con seguro de cancelación USD 36 por persona.',
    'descripcion_details' => array("Argentina Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/3.png',
    'destacado' => true,
  ),
  9 => array(
    'id' => 9,
    'nombre' => 'Japon',
    "continente" => "Asia",
    'precio' => '$36200',
    'descripcion' => 'VISITANDO: Japon Vancouver/ Hope / Kelowna / Revelstoke / Golden / Columbia Ice Field / Canmore /  Banff / Calgar. Incluye: vuelo por American Airlines (Clase turista).',
    'descripcion_details' => array("Japon Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/6.png',
    'destacado' => true,
  ),
  10 => array(
    'id' => 10,
    'nombre' => 'Corea del Sur',
    "continente" => "Asia",
    'precio' => '$36200',
    'descripcion' => 'VISITANDO: Corea del Sur Vancouver/ Hope / Kelowna / Revelstoke / Golden / Columbia Ice Field / Canmore /  Banff / Calgar. Incluye: vuelo por American Airlines (Clase turista).',
    'descripcion_details' => array("Japon Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/6.png',
    'destacado' => false,
  ),
  11 => array(
    'id' => 11,
    'nombre' => 'Egipto',
    "continente" => "Africa",
    'precio' => '$36020',
    'descripcion' => 'VISITANDO: Egipto/ Hope / Kelowna / Revelstoke / Golden / Columbia Ice Field / Canmore /  Banff / Calgar. Incluye: vuelo por American Airlines (Clase turista).',
    'descripcion_details' => array("Egipto Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/4.png',
    'destacado' => true,
  ),
  12 => array(
    'id' => 12,
    'nombre' => 'Nigeria',
    "continente" => "Africa",
    'precio' => '$36550',
    'descripcion' => 'VISITANDO: Nigeria/ Hope / Kelowna / Revelstoke / Golden / Columbia Ice Field / Canmore /  Banff / Calgar. Incluye: vuelo por American Airlines (Clase turista).',
    'descripcion_details' => array("Egipto Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/5.png',
    'destacado' => false,
  ),
  13 => array(
    'id' => 13,
    'nombre' => 'Australia',
    "continente" => "Oceania",
    'precio' => '$360630',
    'descripcion' => 'VISITANDO: Australia/ Hope / Kelowna / Revelstoke / Golden / Columbia Ice Field / Canmore /  Banff / Calgar. Incluye: vuelo por American Airlines (Clase turista).',
    'descripcion_details' => array("Australia Aéreos ES/FE/ES", "04 Noches de alojamiento con régimen según elección.", "Traslados In / Out", "City Tour", "Notas: AÉREOS NETOS NO COMISONABLES.", "Consulte a su ejecutivo de ventas por asistencia al viajero."),
    'url' => 'img/destination/5.png',
    'destacado' => true,
  ),
);

$paisesJSON = json_encode($paisesArr, true);
$file = '../json/paises.json';
file_put_contents($file, $paisesJSON);
